### PR TITLE
Fixed auto completion for symbol emotes.

### PR DESCRIPTION
**Pull request by 23rd**
image

### CODE REVIEW

**Comment by tduva** [comment]
Since I've rewritten and refactored major parts of auto completion this PR has become obsolete. Thanks for the help though, I made sure to include this at an appropriate place in the new version.

**Comment by 23rd** [comment]
Unfortunately, the code from the last commit does not compile. =(

**Comment by tduva** [comment]
Yes, sorry. A new test fails because I renamed some localization string keys. Obviously this will be fixed soon, but in the meantime you can just exclude the test task from running with the `-x test` parameter, such as `gradlew release -x test` (assuming you're using gradle to compile).

**Comment by tduva** [comment]
Tests should run again now.

**Pull request closed without merging**
