### PR TITLE
Migrate build script to Gradle

### PR DESCRIPTION
**Pull request by tmccarthy**
These changes migrate the build system away from the current Netbeans-managed ant script to a Gradle script.

## The current buildscript

A normal Netbeans project is build using `ant` (this is what happens when you hit "build all" in Netbeans). The ant file at `build.xml` refers to a Netbeans-specific ant file at `nbproject/build-impl.xml`, which adds the tasks used to build the project. This is not currently checked in to the Chatty repository, meaning that if you check out the repo and run `ant`, you get something like this:

```
BUILD FAILED
/Users/timothy/Projects/chatty/build.xml:12: Cannot find /Users/timothy/Projects/chatty/nbproject/build-impl.xml imported from /Users/timothy/Projects/chatty/build.xml

```
This can cause problems because contributors to Chatty don't have access to the full build specification. My recollection is that the file at `nbproject/build-impl.xml` changes based on the project settings, meaning that potentially important build information isn't being checked into the git repo.

I think all this could be resolved by simply checking in the `nbproject/build-impl.xml` file, but I've decided to go one step further and try migrating to Gradle.

## The proposed Gradle buildscript

The changes here convert the project to a Gradle project. The build process is specified entirely by the `build.gradle` file. I've tried to make it work mostly the same as it did before, but there are some differences. I hope these will mostly be considered improvements.

### Checking in jar file dependencies

Gradle handles jar file dependencies for you and saves you having to check them in. Instead of checking jar files into the `assets/lib` directory, they are simply specified by name in the `dependencies` block of the `build.gradle` file. This makes upgrading a breeze: just change the version number and you've got the next version. Gradle also automatically handles any transitive dependencies that they might have, and any version conflicts between the libraries used. At the moment this doesn't matter for Chatty, but it could be useful in the future.

### Distributing jar file dependencies

This script uses the fantastic [shadow jar plugin](https://github.com/johnrengelman/shadow) to bundle all the `.class` files Chatty needs into the one jar for the release artifacts. This means that the release zip files no longer need to contain a `lib` directory with the jars: all the necessary class files are included right inside the `Chatty.jar` file. This makes no difference to the user, but it cleans up the installation directory.

### Easy release artifact creation

The `build.gradle` file includes a couple of convenience tasks for assembling the release artifacts: `allPlatformsZip`, `hotkey32Zip` and `hotkey64Zip`, each of which build the respective release artifacts. These are all run together by the `release` task. The zip files created are the same as before (minus the now unneccesary `lib` directory as explained above). So if you want to do a release, just go to the root directory and run `gradlew release`, and the project will compile, run the unit tests, and spit out the release zips to `build/releases`! It even automatically picks up the version number from the current git tag.

### The Gradle wrapper

To build an `ant` project, you have to have it installed. If you want builds to be consistent between multiple developers, you need to make sure everyone has the same `ant` version installed. Gradle gets around this using the [Gradle wrapper](https://docs.gradle.org/current/userguide/gradle_wrapper.html): a small script that downloads and runs the version of Gradle specified in the `wrapper` block in the `build.gradle` file. This way the build system is the same for all developers.

## Using this with Netbeans

I've set the script up so that it should work easily with the latest Netbeans. You'll need to install the [Netbeans Gradle plugin](http://plugins.netbeans.org/plugin/44510/gradle-support). Once you've done that, you can just open the directory as a Netbeans project, and you're set. Running, debugging and building the project should work as before.

I'm not sure how release builds were done previously, but I think the `gradlew release` task is a neat way to do it. Having said that, if the release process (or anything else) is too different when using Gradle, please let me know. I'll try to make it as close to the existing system as possible.

### CODE REVIEW

**Comment by tmccarthy** [comment]
The changes include 4 files that are part of the Gradle wrapper. These are:
 - gradle/wrapper/gradle-wrapper.jar
 - gradle/wrapper/gradle-wrapper.properties
 - gradlew
 - gradlew.bat
These can safely be ignored as far as reviewing the changes is concerned: They're just the small scripts needed for the wrapper.

**Comment by tduva** [comment]
In general I might like it, but I have to understand how it works first, since I don't like to add stuff that I don't understand.

Not sure about that dependency management though.

**Comment by tmccarthy** [comment]
That's fine. I would encourage you to checkout my branch and have a look around if you wanted to get exposure to a more flexible build system than that provided by Netbeans.

The dependency management element of this change is common to almost all Java build tools today. It is the killer feature that has meant that tools like Maven, Ivy and Gradle have largely replaced raw Ant builds in the Java ecosystem. Being able to easily pull in any library in the massive [Maven repositories](http://mvnrepository.com/) often saves you from having to reinvent the wheel.

**Comment by tduva** [comment]
What happens when my internet is down, the repository isn't available or someone deleted the library from the repository. I feel like I'm giving up too much control.

**Comment by tmccarthy** [comment]
Artifacts are [never removed from the Maven central repo](http://stackoverflow.com/questions/9789611/removing-an-artifact-from-maven-central) precisely because of the concerns you've raised.

What Gradle does is download the artifacts into a local cache the first time it is run. From then on, you can build just fine without an internet connection as it retains a local copy. In this respect it isn't much different from normal: you cant *add* new dependencies without an internet connection, but you can keep using the ones you have.

Using the Maven central repo is the industry-wide standard for getting dependencies. If you keep working with JVM languages (not just Java!) you'll run into it and I'm sure you'll like it. Having said that, what I can do instead is change the `build.gradle` script to go back to using the `.jar` files from the `assets/lib` directory just like before. Everything else will work the same: you still get the single `.jar` file, the standardised build, everything. You can even add new dependencies from the Maven repo while taking the existing ones from the `assets/lib` directory. Would you feel more comfortable if we did that?

**Comment by tmccarthy** [comment]
Ok, so I've made a change so that the dependencies block now looks like this:

```
dependencies {
    // Take the .jar files from the assets/lib directory and add them to the compile-time classpath
    compile fileTree(dir: 'assets/lib', include: ['*.jar'])

    testCompile 'junit:junit:4.12'
}
```
So the dependencies are now being take from the `assets/lib` directory instead of being downloaded from the Maven repo. The `.jar` files are the same place they've always been.

You could even mix and match styles. If (for example) you wanted to add the wonderful Guava library from Google, you could either add the `.jar` file to the `assets/lib` directory, or you could get it from Maven like so:

```
dependencies {
    // Take the .jar files from the assets/lib directory and add them to the compile-time classpath
    compile fileTree(dir: 'assets/lib', include: ['*.jar'])
    compile group: 'com.google.guava', name: 'guava', version: '19.0'

    testCompile 'junit:junit:4.12'
}
```

**Comment by tduva** [comment]
I finally got around to looking at Gradle and have a few questions.

I noticed that the build script runs the git command to get the version number. I'm not sure I like depending on the user having git installed and in their PATH. And indeed when I try to run it, it throws an error because it can't find git. I don't run git from the standard Windows command prompt, so I don't need it in the system path. Another way would be to read the version from the `Chatty.java` file, although I'm not sure how well that would work.

The global hotkeys feature is disabled by a variable in the `Chatty.java`, except for the hotkey versions. This is basicially to disable a warning that the jintellitype files couldn't be loaded. I assume it's not very convenient to compile two versions of the Chatty.jar, with the value of that variable changed accordingly. I suppose it could only output the warning when there is actually a global hotkey added in the settings, so there would be no need to have different jars.

Also I haven't found anything in the build script that tells it which Java version it should compile it for. Wouldn't that make sense (like `sourceCompatibility = 1.8`)?

**Comment by tmccarthy** [comment]
Yeah these are all good points.

Of course, you're right that the build process shouldn't depend on `git` being on the path. This can be easily fixed by instead using the [`org.ajoberstar.grgit`](https://github.com/ajoberstar/gradle-git) Gradle plugin to interface with git. This way we can still call `git describe`, even if it isn't on the path.

The bigger problem though, as you point out, is that we have to get the version information and the correct `HOTKEY` flag into `Chatty.java`.

The way I see it, there are two options:

1. We keep getting the version information from git, and then we insert this (along with the `HOTKEY` flag) into the compiled code. This actually isn't too tricky: I'd just have to write a little, custom Gradle task to generate a `.properties` file or somesuch with the needed info. Then we can put this file into the jar, and read it at runtime.
2. We wind this all back a bit. Instead of getting the version from `git`, we just pull it directly from `Chatty.java`. Instead of having a `releaseZips` task that packages *all* of the zip files, we just use the individual `allPlatformsZip`, `hotkey32Zip` and `hotkey64Zip` tasks to package releases. This way, you can manually edit the `HOTKEY` flag as needed for each of them.

In this case, I think it might be easiest to just go with option 2. I think it's a lot closer to your current workflow, and (importantly), it'll play nicely with Netbeans. I haven't used Netbeans with Gradle in a long time, but IDEs can get fussy when compile-time code generation gets involved.

In any case, choosing option 2 doesn't preclude eventually exploring options similar to 1.

I'm gonna go ahead and make changes as per option 2. Let me know if you've got any more thoughts.

**Comment by tduva** [comment]
I've already [changed](5aefd9bc8c59c385727637a9a2d4c17ecd82539d) the `HOTKEY` flag to be always `true` on Windows and just not output any warning if the user isn't using that feature. So changing that flag in any way shouldn't be required.

Getting the version number from the `Chatty.java` would be my preferred way, if that is easily possible.

**Comment by tmccarthy** [comment]
Ok then. I've made a change to read the version from `Chatty.java`. I'm doing it with regex, which is a little brittle, but should be ok.

Given you've already solved the `HOTKEY` problem, I'll leave the `release` and `releaseZips` tasks as is.

I've forgotten to add the `sourceCompatibility` flag. I'll do that now.

**Comment by tmccarthy** [comment]
Ok that's done. Let me know what you think!

**Comment by tduva** [comment]
Seems good. I've ran into a problem with the regex though, it tries to use the whole matched line in the filename. I changed it to `return matcher[0][1]` since I assumed that 0 would be the whole match and 1 the first group, as with `Matcher.group(int)`.

I also added `version = null` to the `shadowJar { }` section, because I'd rather have it just be `Chatty.jar` and the version only in the .zip filename. I assume setting `version = null` inside that task doesn't affect the rest of the script?

**Comment by tmccarthy** [comment]
Ok I've fixed that matcher issue.

Normally, changing a variable within a block of a Gradle script would affect its value in the rest of the script. If (for example) you set the `sourceCompatibility` flag inside the `shadowJar` block, it would affect the rest of the script. In this case, though, the `shadowJar` block has its own `version` attribute, and that's the one you're setting inside the block. So yes, this is the way to remove the version from the jar file name.

**Comment by tduva** [comment]
Looks good.

**Pull request merged**
