### PR TITLE
Mention an user in the right-click menu (part of issue #113)

### PR DESCRIPTION
**Pull request by Number6406**
As asked in the #113 issue, but only with right-click for the moment. I'm currently looking for a double-click solution too.
I also added a "_forceSpaceAfter_" boolean in the **insertText()** functions in order to force space concat when it is needed.

### CODE REVIEW

**Comment by tduva** [comment]
I'm not sure I want to clutter up the menu any more.

**Comment by Number6406** [comment]
Okay ! Thanks you for your answer anyway !

**Comment by tduva** [comment]
If you just want to add a space no matter what, you wouldn't need an argument for that, you could just append it to the String that gets inserted.

If anything then maybe `(forceSpaceAfter || !after.isEmpty()) && !after.startsWith(" ")` so you can have a command like `/insertmention` that would force a space only if there is no following space already.

**Comment by Number6406** [comment]
You're right, thanks for the explanations 👍 
I thought it was just "cleaner" to add this boolean.

**Pull request closed without merging**
