### PR TITLE
Fix Clip not closing after playback in util/Sound.java

### PR DESCRIPTION
**Pull request by GhettoGirl**
Close the Clip after playback has finished to prevent like one million "ALSA plug-in [java]" entries in the ALSA and/or PulseAudio mixer under Linux and other UNIX-like Operating Systems.

The fix was very simple.
I just added a LineListener to the Clip.

chatty-fix

### CODE REVIEW

**Comment by tduva** [comment]
Why does the whole file show as changed?

**Comment by GhettoGirl** [comment]
This is because my Java IDE converted all *DOS line breaks* ```\r\n (2 bytes)``` into *UNIX line breaks* ```\n (1 byte)```. This happens automatically as soon as I save the file. (File/Save Preference)

**Comment by tduva** [comment]
Weird, it showed `core.autocrlf` as enabled in my repository, but I guess it somehow wasn't? Anyway, I added a `.gitattributes` file now and normalized all line endings in one commit, better than changing it in commits where actually other stuff is changed.

**Comment by GhettoGirl** [comment]
I reforked you repo, since I fucked something up in my fork after your line endings commit. I'm closing this pull request now and open a new one.

**Pull request closed without merging**
