### PR TITLE
added the option to disable userlist by default

### PR DESCRIPTION
**Pull request by coolglen**
Added a setting in the window tab to disable the userlist by default. 

This is my first time contributing to a project I hope I have done everything right.

### CODE REVIEW

**Comment by tduva** [comment]
Can you please rename the setting to `userlistEnabled` (default to true) and change the logic accordingly. I think that makes more sense this way around and the other userlist settings already start with ´userlist` as well.

Also I think you have a typo in `defaultUserlistVisableState` and `setDefaultUserlistVisableState`.

**Comment by coolglen** [comment]
I have made the changes, let me know if there's anything else you would like changed.

**Comment by GhettoGirl** [comment]
IMO you could rebase all 3 commits into 1. That would I do at least.
```git rebase -i HEAD~3```
```git
pick ...
fixup ...
fixup ...
```

The git history looks much cleaner than. :smile:

**Comment by tduva** [comment]
I'm squashing the commits when merging anyway. :)

**Comment by RedSnt** [comment]
@coolglen My hero~! I hope it wasn't too much work.

**Pull request merged**
