### PR TITLE
Add automatic log splits and channel subdirectory options

### PR DESCRIPTION
**Pull request by Mheetu**
This PR adds the ability to automatically split log files and group them into subdirectories.

Log files can be split daily, weekly, or monthly and will be prefixed with a date stamp `yyyy-MM-dd_`.
<small>(Note: Weekly and monthly log splits will be dated as the first day of that week or month, respectively. Not the day that the file was created.)</small>

The subdirectories option will organize logs into channel subdirectories such that all logs from `#mheetu` will be located in `logs/#mheetu/yyyy-MM-dd_#mheetu.log`.

Settings screen:

Also cleaned up and added some docblocks to `LogFile`.

### CODE REVIEW

**Comment by Mheetu** [comment]
As an alternative approach to this, I wouldn't mind seeing logs stored in an SQLite or Mongo database at some point.

**Comment by Mheetu** [comment]
@tduva, any reason as to why this was never merged? Would it be worth my time to resolve the conflicts and push an update?

**Comment by tduva** [comment]
Sorry I didn't answer for so long, I want to understand the changes myself before I merge something and I had loads of other things to do with Twitch releasing new features all the time. :cat: 

This looks pretty good. :+1: I've had an eye on this for some time and wanted to look into it again for the next update.

**Comment by Mheetu** [comment]
Will do, the next few days are going to be hectic for me but I'll look into it when I can. :)

**Comment by Mheetu** [comment]
Finished some other work early so I went ahead and resolved the conflicts. I did a quick test and everything seems to be in order but I've also not used any of the releases since I initially submit this PR, so I'm not too familiar with changes made since then.

I'll be using this build myself from here forward, or at least until it's merged, so I'll keep an eye out for any regressions that may have slipped by while resolving the conflicts. Please also review the changes yourself before merging.

**Comment by tduva** [comment]
Why did you change the suffix separator to `_`?

Also did you amend your original commit?

**Comment by Mheetu** [comment]
Sorry, I'm used to working on projects where they prefer a clean Git log and would rather a rebase when resolving conflicts in an outdated pull request.

Not sure what you're referring to in regards to the 'suffix separator', what line? You stated that I changed it… do you mean I changed it since my first PR or that it's different from the current release?

**Comment by tduva** [comment]
The commits will be squashed when it's merged.

I mean [this line](https://github.com/Mheetu/chatty/blob/ad9bf64e37fe5bea36c5d6960aedfe51ee82a57a/src/chatty/util/chatlog/LogFile.java#L75), it originally was `-`.

**Comment by Mheetu** [comment]
Oh, I don't even remember changing that, it was done in my initial PR back in March. Anyway, I'd imagine I changed it because I'm using hyphens in the dates. It makes the file names more readable when browsing a list of them. The channel names start with a hash tag anyway so confusion shouldn't be an issue.

image

**Comment by tduva** [comment]
No, this is at the end of the filename, in case the file is already locked, for example when you have several instances of the program running. It's an edge case really. I'll just change it back myself, don't worry about it.

```
2016-11-03_#dansgaming.log
2016-11-03_#dansgaming-1.log
```

**Comment by Mheetu** [comment]
You're right, I just realized that... sorry, I just rolled out of bed. lol

I'm honestly not sure why that was changed. I've never had a file be locked or have to use that alternative naming scheme and have no preference on the matter.

Would you like it to be reverted back to a hyphen?

**Comment by tduva** [comment]
If you want to do it, I can also do it after merging, doesn't really matter much.

**Comment by Mheetu** [comment]
Done. :)

**Pull request merged**
