### PR TITLE
[not for merge] [WIP] multilanguage support

### PR DESCRIPTION
**Pull request by magiruuvelvet**
**Not for merge, includes private changes!**

Thread meant to be for discussions.

---

I recently started working on some multilingual support for Chatty and implemented a class which parses bundled language packs from the JAR file. All found strings are stored into a map (key = string id, value = translation).

I already translated some stuff in Chatty to test it out.

Translations are received like this around the application and falls back to the builtin strings if it couldn't be found in the language pack.

```java
Chatty.lang.GET("STRING_ID", "Fallback (English)")
```

I came up with the idea some days ago because a colleague of mine doesn't speak English at all and had serious trouble using your app so I started translating it in a way that more languages can be added easily later.

What do you think about translating Chatty into other languages? Twitch did that as well and has communities around the world.

### CODE REVIEW

**Comment by tduva** [comment]
One problem with this is that the help files won't match the program. And it's hard enough to keep everything up-to-date as it is.

**Comment by tduva** [comment]
I suppose for people that understand very little English it would be better to have the basics interface translated, but for more advanced usage, like reading the help for the more advanced settings, I think it would be impractical to translate.

**Comment by magiruuvelvet** [comment]
I would agree with just the translation of the basic functionalities to make it easier for non English speakers to use the app. The help (documentation) is really huge and would require a lot of work to keep up-to-date.

So basically translate most of the UI (like Context Menus, Dialogs) and keep the more advanced features and the documentation in English.

As a side note I'd like to mention: While creating the string ids I found a lot of `+` in some places which I needed to change to `String.format` to make them translatable to languages which have a different grammer than English, using a `+` for strings would make this impossible to probably translate this parts of the app.

**Comment by tduva** [comment]
Is there any reason you aren't using `java.util.ResourceBundle` and `java.util.Locale`?

**Comment by magiruuvelvet** [comment]
Laziness, I rushed the implementation without researching before what Java has to offer. I'm checking out this 2 classes now what they do and how to use them.

**Comment by tduva** [comment]
There's a quick introduction here: https://docs.oracle.com/javase/tutorial/i18n/intro/quick.html

**Comment by tduva** [comment]
I might do some testing of my own, it should be easy to convert your translation files if these classes work out well.

**Comment by tduva** [comment]
I added an issue (#221) for discussion, since this goes further than this PR and it might be easier for others to find there.

**Comment by magiruuvelvet** [comment]
Sure thing.

**Pull request closed without merging**
